name: PR Coding Standards Check

on:
  pull_request:
    branches:
      - main # or your default branch name

jobs:
  coding-standards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: phpcs, php-cs-fixer

      - name: Check coding standards with PHP_CodeSniffer
        run: |
          composer install
          vendor/bin/phpcs --standard=PSR2 src/ # Adjust the standard and path as needed

      - name: Automatically fix code issues with PHP-CS-Fixer
        run: |
          vendor/bin/php-cs-fixer fix --rules=@PSR2 --using-cache=no src/ # Adjust the rules and path as needed

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -u
          git commit -m "Fix coding standards issues" || echo "No changes to commit"
          git push
